version: "3"
services:
  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
        
  elon:
    depends_on: 
      rabbit:
        condition: service_healthy
    build: ./ColiseumWebApp/
    environment:
      - PLAYER=Elon
    ports:
      - "5001:80"
    
  mark:
    depends_on:
      rabbit:
        condition: service_healthy
    build: ./ColiseumWebApp/
    environment:
      - PLAYER=Mark
    ports:
      - "5002:80"